// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "style": {
      name: "style",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "avatar-group": {
      name: "avatar-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/avatar-group.tsx")),
      source: "",
      chunks: []
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors": {
      name: "github-contributors",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/github-contributors.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/github-contributors.tsx")),
      source: "",
      chunks: []
    },
    "phone-card": {
      name: "phone-card",
      description: "",
      type: "registry:ui",
      registryDependencies: ["lazy-video"],
      files: [{
        path: "registry/default/ui/phone-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/phone-card.tsx")),
      source: "",
      chunks: []
    },
    "lazy-video": {
      name: "lazy-video",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/lazy-video.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/lazy-video.tsx")),
      source: "",
      chunks: []
    },
    "vercel-tabs": {
      name: "vercel-tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/vercel-tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/vercel-tabs.tsx")),
      source: "",
      chunks: []
    },
    "magnetic": {
      name: "magnetic",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/magnetic.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/magnetic.tsx")),
      source: "",
      chunks: []
    },
    "video-player": {
      name: "video-player",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/video-player.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/video-player.tsx")),
      source: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-mobile.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.ts")),
      source: "",
      chunks: []
    },
    "avatar-group-demo": {
      name: "avatar-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-demo.tsx")),
      source: "",
      chunks: []
    },
    "avatar-group-truncation-demo": {
      name: "avatar-group-truncation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-truncation-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-truncation-demo.tsx")),
      source: "",
      chunks: []
    },
    "avatar-group-rtl-demo": {
      name: "avatar-group-rtl-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-rtl-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-rtl-demo.tsx")),
      source: "",
      chunks: []
    },
    "avatar-group-icons-demo": {
      name: "avatar-group-icons-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-icons-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-icons-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-variants-demo": {
      name: "button-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-variants-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-sizes-demo": {
      name: "button-sizes-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-sizes-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-sizes-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-icon-demo": {
      name: "button-icon-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-icon-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-icon-demo.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors-demo": {
      name: "github-contributors-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["github-contributors"],
      files: [{
        path: "registry/default/examples/github-contributors-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/github-contributors-demo.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors-limit-demo": {
      name: "github-contributors-limit-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["github-contributors"],
      files: [{
        path: "registry/default/examples/github-contributors-limit-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/github-contributors-limit-demo.tsx")),
      source: "",
      chunks: []
    },
    "phone-card-demo": {
      name: "phone-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-card"],
      files: [{
        path: "registry/default/examples/phone-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/phone-card-demo.tsx")),
      source: "",
      chunks: []
    },
    "phone-card-image-demo": {
      name: "phone-card-image-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-card"],
      files: [{
        path: "registry/default/examples/phone-card-image-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/phone-card-image-demo.tsx")),
      source: "",
      chunks: []
    },
    "vercel-tabs-demo": {
      name: "vercel-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["vercel-tabs"],
      files: [{
        path: "registry/default/examples/vercel-tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/vercel-tabs-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-demo": {
      name: "magnetic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-intensity-demo": {
      name: "magnetic-intensity-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-intensity-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-intensity-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-range-demo": {
      name: "magnetic-range-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-range-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-range-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-action-area-demo": {
      name: "magnetic-action-area-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-action-area-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-action-area-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-cards-demo": {
      name: "magnetic-cards-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-cards-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-cards-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-demo": {
      name: "video-player-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-compact-demo": {
      name: "video-player-compact-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-compact-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-compact-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-playlist-demo": {
      name: "video-player-playlist-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-playlist-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-playlist-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-callbacks-demo": {
      name: "video-player-callbacks-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-callbacks-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-callbacks-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-quality-demo": {
      name: "video-player-quality-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-quality-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-quality-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-captions-demo": {
      name: "video-player-captions-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-captions-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-captions-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-timestamp-demo": {
      name: "video-player-timestamp-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-timestamp-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-timestamp-demo.tsx")),
      source: "",
      chunks: []
    },
  },
}
