// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "style": {
      name: "style",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "avatar-group": {
      name: "avatar-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/avatar-group.tsx")),
      source: "",
      chunks: []
    },
    "animated-table": {
      name: "animated-table",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/animated-table.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/animated-table.tsx")),
      source: "",
      chunks: []
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      chunks: []
    },
    "file-tree": {
      name: "file-tree",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/file-tree.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/file-tree.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors": {
      name: "github-contributors",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/github-contributors.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/github-contributors.tsx")),
      source: "",
      chunks: []
    },
    "phone-card": {
      name: "phone-card",
      description: "",
      type: "registry:ui",
      registryDependencies: ["lazy-video"],
      files: [{
        path: "registry/default/ui/phone-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/phone-card.tsx")),
      source: "",
      chunks: []
    },
    "lazy-video": {
      name: "lazy-video",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/lazy-video.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/lazy-video.tsx")),
      source: "",
      chunks: []
    },
    "vercel-tabs": {
      name: "vercel-tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/vercel-tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/vercel-tabs.tsx")),
      source: "",
      chunks: []
    },
    "magnetic": {
      name: "magnetic",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/magnetic.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/magnetic.tsx")),
      source: "",
      chunks: []
    },
    "video-player": {
      name: "video-player",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/video-player.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/video-player.tsx")),
      source: "",
      chunks: []
    },
    "calender": {
      name: "calender",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/calender.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/calender.tsx")),
      source: "",
      chunks: []
    },
    "code-block": {
      name: "code-block",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/code-block.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/code-block.tsx")),
      source: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-mobile.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.ts")),
      source: "",
      chunks: []
    },
    "avatar-group-demo": {
      name: "avatar-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-demo.tsx")),
      source: "",
      chunks: []
    },
    "avatar-group-truncation-demo": {
      name: "avatar-group-truncation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-truncation-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-truncation-demo.tsx")),
      source: "",
      chunks: []
    },
    "avatar-group-rtl-demo": {
      name: "avatar-group-rtl-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-rtl-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-rtl-demo.tsx")),
      source: "",
      chunks: []
    },
    "avatar-group-icons-demo": {
      name: "avatar-group-icons-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-group"],
      files: [{
        path: "registry/default/examples/avatar-group-icons-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-group-icons-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-basic-demo": {
      name: "animated-table-basic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-basic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-basic-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-sort-demo": {
      name: "animated-table-sort-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-sort-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-sort-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-search-demo": {
      name: "animated-table-search-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-search-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-search-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-select-demo": {
      name: "animated-table-select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-select-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-expand-demo": {
      name: "animated-table-expand-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-expand-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-expand-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-column-demo": {
      name: "animated-table-column-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-column-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-column-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-pagination-demo": {
      name: "animated-table-pagination-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-pagination-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-pagination-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-full-demo": {
      name: "animated-table-full-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-full-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-full-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-variants-demo": {
      name: "button-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-variants-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-sizes-demo": {
      name: "button-sizes-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-sizes-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-sizes-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-icon-demo": {
      name: "button-icon-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-icon-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-icon-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-basic-demo": {
      name: "file-tree-basic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-basic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-basic-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-expandable-demo": {
      name: "file-tree-expandable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-expandable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-expandable-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-full-expanded-demo": {
      name: "file-tree-full-expanded-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-full-expanded-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-full-expanded-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-selectable-demo": {
      name: "file-tree-selectable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-selectable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-selectable-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-custom-icons-demo": {
      name: "file-tree-custom-icons-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-custom-icons-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-custom-icons-demo.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors-demo": {
      name: "github-contributors-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["github-contributors"],
      files: [{
        path: "registry/default/examples/github-contributors-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/github-contributors-demo.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors-limit-demo": {
      name: "github-contributors-limit-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["github-contributors"],
      files: [{
        path: "registry/default/examples/github-contributors-limit-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/github-contributors-limit-demo.tsx")),
      source: "",
      chunks: []
    },
    "phone-card-demo": {
      name: "phone-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-card"],
      files: [{
        path: "registry/default/examples/phone-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/phone-card-demo.tsx")),
      source: "",
      chunks: []
    },
    "phone-card-image-demo": {
      name: "phone-card-image-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-card"],
      files: [{
        path: "registry/default/examples/phone-card-image-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/phone-card-image-demo.tsx")),
      source: "",
      chunks: []
    },
    "vercel-tabs-demo": {
      name: "vercel-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["vercel-tabs"],
      files: [{
        path: "registry/default/examples/vercel-tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/vercel-tabs-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-demo": {
      name: "magnetic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-intensity-demo": {
      name: "magnetic-intensity-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-intensity-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-intensity-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-range-demo": {
      name: "magnetic-range-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-range-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-range-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-action-area-demo": {
      name: "magnetic-action-area-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-action-area-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-action-area-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-cards-demo": {
      name: "magnetic-cards-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-cards-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-cards-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-demo": {
      name: "video-player-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-compact-demo": {
      name: "video-player-compact-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-compact-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-compact-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-playlist-demo": {
      name: "video-player-playlist-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-playlist-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-playlist-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-callbacks-demo": {
      name: "video-player-callbacks-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-callbacks-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-callbacks-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-quality-demo": {
      name: "video-player-quality-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-quality-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-quality-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-captions-demo": {
      name: "video-player-captions-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-captions-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-captions-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-timestamp-demo": {
      name: "video-player-timestamp-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-timestamp-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-timestamp-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-basic-demo": {
      name: "calendar-basic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-basic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-basic-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-range-demo": {
      name: "calendar-range-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-range-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-range-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-multiple-demo": {
      name: "calendar-multiple-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-multiple-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-multiple-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-time-demo": {
      name: "calendar-time-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-time-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-time-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-presets-demo": {
      name: "calendar-presets-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-presets-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-presets-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-constraints-demo": {
      name: "calendar-constraints-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-constraints-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-constraints-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-full-demo": {
      name: "calendar-full-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-full-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-full-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-demo": {
      name: "code-block-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-variants-demo": {
      name: "code-block-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-variants-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-animations-demo": {
      name: "code-block-animations-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-animations-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-animations-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-compare-demo": {
      name: "code-block-compare-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-compare-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-compare-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-tabs-demo": {
      name: "code-block-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-tabs-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-terminal-demo": {
      name: "code-block-terminal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-terminal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-terminal-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-glass-demo": {
      name: "code-block-glass-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-glass-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-glass-demo.tsx")),
      source: "",
      chunks: []
    },
  },
}
